### ISSUE TITLE
NativeScript Branch: enable AOT

### ISSUE THREAD

**Issue by syjer** [alfio-event/Alf.ioBackoffice#10]
In theory, we "only" need to add the nativescript-dev-webpack plugin (https://www.nativescript.org/blog/nativescript-25-is-now-available ) -> http://docs.nativescript.org/angular/tooling/bundling-with-webpack.html

**Comment by syjer** [comment]
current issues:

 - nativescript-vibrate plugin: in package.json the main should be "vibrate" and not "vibrate.js"
 - error in loading the barcode imports
 - error as reported in https://github.com/telerik/nativescript-ui-samples/issues/161

**Comment by syjer** [comment]
note: using the template ng, aot work:

>tns create my-hallo-world --template ng
>cd my-hallo-world
>npm install --save-dev nativescript-dev-webpack
>npm run start-android-bundle

**Comment by cbellone** [comment]
implemented
