### ISSUE TITLE
Eventlist Item Box not completly clickable (iOS and Android)

### ISSUE THREAD

**Issue by mg-1999** [alfio-event/Alf.ioBackoffice#15]
When you connect to the server and see the event listing. You can click on the name of the event to go to it. But not on its icon or arrow on the left.

 I think that the whole box should be clickable.

**Comment by gi4nks** [comment]
What do you think about putting the tap event on the gridlayout? Like follows:
`template: `<GridLayout columns="35, *, 35" *ngIf="event" (tap)="select()">
                    <Label text="&#xf1df;" col="0" class="icon icon-1-5x person-icon text-primary text-center v-middle"></Label>
                    <StackLayout col="1" class="medium-spacing" orientation="vertical">
                        <Label [text]="event.name" class="eventName" textWrap="true"></Label>
                        <Label text="{{ event.begin | date:'short' }} - {{ event.end | date:'short' }}" *ngIf="!event.oneDay"></Label>
                        <Label text="{{ event.begin | date:'shortDate' }} {{ event.begin | date:'shortTime' }} - {{ event.end | date:'shortTime' }}" *ngIf="event.oneDay"></Label>
                        <Label [text]="event.location"></Label>
                    </StackLayout>
                    <Label [text]="iconText" col="2" class="icon icon-1-5x person-icon text-center" *ngIf="list"></Label>
                </GridLayout>`,`

**Comment by cbellone** [comment]
This issue can now be tested on your devices by:
- entering the Beta Program on Google Play (https://play.google.com/store/apps/details?id=alfio.scan)
- downloading the Beta app on iOS TestFlight: https://testflight.apple.com/join/glG9ICZT
