### ISSUE TITLE
Invalid scan makes all following scans fail

### ISSUE THREAD

**Issue by salmar** [alfio-event/Alf.ioBackoffice#16]
When scanning an invalid QR (UUID), an item in the attendee list is shown with the message "Synchronisation in progress". All following valid scans are also displayed with the same message making it impossible to further scan QRs.

**Steps to reproduce the behavior:**
1. Scan a valid UUID and check the attendee name shows up in the attendee list
2. Scan an invalid UUID (it will appear with the message "Synchronisation in progress")
3. Scan a valid UUID again, you will see the attendee name is not resolved and the UUID with the "Synchronisation in progress" message appears in the list instead. Repeat the process again, all scans will display the same message with no attendee data.

**Expected behavior**
An invalid scan should display an item in the list with an invalid message, the current message gives a false impression to the user who might think it's synchronising. It would be also helpful to be able to delete items from the list.

All valid scans after an invalid scan should work as expected, resolving the attendee data and displaying it in the list.

**Screenshots**
![invalid-scan](https://user-images.githubusercontent.com/122109/54858211-cbbe5580-4d03-11e9-811c-774de971c227.png)

**Smartphone:**
 - Device: OnePlus 6
 - OS: OxygenOS 9.0.4 (Android 9)

**Comment by cbellone** [comment]
The fix for this issue can now be tested on your devices by:
- entering the Beta Program on Google Play (https://play.google.com/store/apps/details?id=alfio.scan)
- downloading the Beta app on iOS TestFlight: https://testflight.apple.com/join/glG9ICZT

**Comment by cbellone** [comment]
Tested
