### ISSUE TITLE
Scanning the same QR multiple times should notify the user

### ISSUE THREAD

**Issue by salmar** [alfio-event/Alf.ioBackoffice#17]
When first scanning a QR, a toast is displayed notifying the scan was enqueued (along with vibration) and the data is added to the attendee list. The second time the same QR is scanned, no message is displayed (no vibration either), feels like the scanner is not able to read the QR. It would be helpful to get a message notifying the QR has already been scanned.

**Comment by cbellone** [comment]
The fix for this issue can now be tested on your devices by:
- entering the Beta Program on Google Play (https://play.google.com/store/apps/details?id=alfio.scan)
- downloading the Beta app on iOS TestFlight: https://testflight.apple.com/join/glG9ICZT

**Comment by cbellone** [comment]
Tested
