### ISSUE TITLE
Be able to customize the data displayed in the attendee list

### ISSUE THREAD

**Issue by salmar** [alfio-event/Alf.ioBackoffice#18]
When scanning a QR, the name and email of the attendee is displayed in the attendee list. As an organizer I would like to customize the data the sponsor can see on the app (e.g. maybe name and company but not email)

**Comment by gi4nks** [comment]
So, there are 2 situation where email are shown in the event details:
- event-detail page in the sponsor section: email to be replaced by uuid
- event-detail page in the staff section: email to be removed

**Comment by cbellone** [comment]
The fix for this issue can now be tested on your devices by:
- entering the Beta Program on Google Play (https://play.google.com/store/apps/details?id=alfio.scan)
- downloading the Beta app on iOS TestFlight: https://testflight.apple.com/join/glG9ICZT

**Comment by cbellone** [comment]
Tested
